version: '2'
services:
  website: 
    container_name: website
    image: php:7.2-apache
    depends_on:
      - api   
    environment:
      - USERNAME=${API_USER}
      - PASSWORD=${API_PWD}
    networks:
      - webapp-network
    volumes:
      - ./website:/var/www/html
    ports:
      - "50:80"
  api:
    container_name: api
    image: registry.gitlab.com/fil-rouge2/fil-rouge/fil-rouge
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge      
